#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "$0")/.." && pwd)"
export CLUSTERCOST_KUBECONFIG="${CLUSTERCOST_KUBECONFIG:-$HOME/.kube/config}"
export CLUSTERCOST_CPU_HOUR_PRICE="${CLUSTERCOST_CPU_HOUR_PRICE:-0.04}"
export CLUSTERCOST_MEMORY_GIB_HOUR_PRICE="${CLUSTERCOST_MEMORY_GIB_HOUR_PRICE:-0.004}"
export CLUSTERCOST_CLUSTER_NAME="${CLUSTERCOST_CLUSTER_NAME:-dev-cluster}"
export CLUSTERCOST_LOG_LEVEL="${CLUSTERCOST_LOG_LEVEL:-debug}"

go run "$ROOT_DIR/cmd/agent"
