apiVersion: v1
kind: Namespace
metadata:
  name: clustercost
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: clustercost-agent
  namespace: clustercost
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: clustercost-agent
rules:
  - apiGroups: [""]
    resources: ["pods", "nodes", "namespaces", "services", "endpoints"]
    verbs: ["get", "list", "watch"]
  - apiGroups: ["metrics.k8s.io"]
    resources: ["pods"]
    verbs: ["get", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: clustercost-agent
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: clustercost-agent
subjects:
  - kind: ServiceAccount
    name: clustercost-agent
    namespace: clustercost
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: clustercost-agent
  namespace: clustercost
spec:
  selector:
    matchLabels:
      app: clustercost-agent
  template:
    metadata:
      labels:
        app: clustercost-agent
    spec:
      serviceAccountName: clustercost-agent
      hostNetwork: true
      hostPID: true
      containers:
        - name: agent
          image: ghcr.io/you/clustercost-agent-k8s:dev
          imagePullPolicy: IfNotPresent
          securityContext:
            privileged: true
          env:
            - name: NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
            - name: CLUSTERCOST_EBPF_METRICS_ENABLED
              value: "true"
            - name: CLUSTERCOST_NETWORK_ENABLED
              value: "true"
            - name: CLUSTERCOST_EBPF_METRICS_MAP_PATH
              value: "/sys/fs/bpf/clustercost/metrics"
            - name: CLUSTERCOST_EBPF_MAP_PATH
              value: "/sys/fs/bpf/clustercost/flows"
            - name: CLUSTERCOST_EBPF_METRICS_OBJECT
              value: "/opt/clustercost/bpf/metrics.bpf.o"
            - name: CLUSTERCOST_EBPF_NET_OBJECT
              value: "/opt/clustercost/bpf/flows.bpf.o"
            - name: CLUSTERCOST_EBPF_METRICS_CGROUP_PATH
              value: "/sys/fs/cgroup"
            - name: CLUSTERCOST_EBPF_NET_CGROUP_PATH
              value: "/sys/fs/cgroup"
            - name: CLUSTERCOST_CGROUP_ROOT
              value: "/sys/fs/cgroup"
          volumeMounts:
            - name: bpf
              mountPath: /sys/fs/bpf
            - name: cgroup
              mountPath: /sys/fs/cgroup
              readOnly: true
            - name: btf
              mountPath: /sys/kernel/btf
              readOnly: true
          ports:
            - name: http
              containerPort: 8080
          readinessProbe:
            httpGet:
              path: /agent/v1/readyz
              port: http
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /agent/v1/health
              port: http
            initialDelaySeconds: 10
            periodSeconds: 20
          resources:
            requests:
              cpu: "200m"
              memory: "256Mi"
            limits:
              cpu: "1"
              memory: "1Gi"
      volumes:
        - name: bpf
          hostPath:
            path: /sys/fs/bpf
        - name: cgroup
          hostPath:
            path: /sys/fs/cgroup
        - name: btf
          hostPath:
            path: /sys/kernel/btf
---
apiVersion: v1
kind: Service
metadata:
  name: clustercost-agent
  namespace: clustercost
spec:
  selector:
    app: clustercost-agent
  ports:
    - name: http
      port: 8080
      targetPort: http
